name: Sync Upstream

on:
  schedule:
    - cron: "0 * * * *"  # 每小时同步一次
  workflow_dispatch: # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Sync upstream changes
        uses: repo-sync/push-action@v1
        with:
          source_repo: "Putarku/MoviePilot-Help"  # 替换为原项目的作者和仓库名
          source_branch: "main"           # 原项目的分支名
          destination_branch: "main"      # 你 fork 仓库的分支名
          github_token: ${{ secrets.GITHUB_TOKEN }}
